config/routes.rb
Serverfu4::Application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "overview/index"
  root to: "overview#index"

  resources :credential_types
  resources :credentials
  resources :ips
  resources :domains
  resources :sites
  resources :clients
  resources :servers
  resources :hosts
  resources :notes
  resources :contacts
  resources :phones
  resources :emails
  resources :addresses
  resources :states
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many :notes, :as => :noteable
  has_many :contacts, :as => :contactable
  has_many :servers
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    host = Host.find(:all, order: 'name').first
    if host != nil then
      redirect_to host_url(host)
    end
  end

  def show
    begin
      @host = Host.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to hosts_path
    else
      @host_servers = @host.servers.order(:name).page params[:body_page]
      @host_contacts = @host.contacts.order(:last_name).page params[:body_page]
      @host_notes = @host.notes.order('created_at DESC').page params[:body_page]
  
      @hosts = Host.order('name').page params[:sidebar_page]
  
      @new_host = Host.new
      @new_server = Server.new
      @new_contact = Contact.new
      @new_note = Note.new
    end
  end

  def create
    @host = Host.new new_host_params
    if @host.save
      redirect_to @host,
        notice: (t 'success.create', thing: 'Host')
    else
      render action: "create"
    end
  end

  def update
    @host = Host.find(params[:id])

    if params[:host]
      respond_to do |format|
        if @host.update_attributes(host_params)
          format.html { redirect_to @host,
            notice: (t 'success.update', thing: 'Host') }
          format.json { respond_with_bip(@host) }
        else
          format.html { render :action => "edit" }
          format.json { respond_with_bip(@host) }
        end
      end
    end

  end

  def destroy
    @host = Host.find(params[:id])

    if @host.destroy
      redirect_to hosts_path,
        notice: (t 'success.delete', thing: @host.name)
    else
      flash.now[:error] = t 'error.create', thing: 'Note'
    end
  end


  private

  def host_params
    params.require(:host).permit(:name)
  end

  def new_host_params
    params.require(:new_host).permit(:name)
  end

  def server_params
    params.require(:new_server).permit(:name)
  end

  def contact_params
    params.require(:new_contact).permit(:description)
  end

  def note_params
    params.require(:new_note).permit(:note)
  end

end

app/views/hosts/index.html.haml
- content_for :sidebar do
  %h3 Hosts

%ul.nav.nav-tabs
  %p No hosts have been added yet.

app/views/hosts/show.html.haml
- content_for :sidebar do
  %ul.list-group
    - @hosts.each do |host|
      %li.list-group-item{:class => ('active' if @host.id == host.id)}
        = best_in_place host, :name, type: :input
        - if host.servers.length == 0
          = link_to host_url(host, sidebar_page: params['sidebar_page']),
                    confirm: t('confirm.delete', name: host.name),
                    method: :delete do
            %span.glyphicon.glyphicon-remove
        - else
          %span.glyphicon.glyphicon-remove.text-muted
        = link_to host_url(host, sidebar_page: params['sidebar_page']) do
          %span.glyphicon.glyphicon-chevron-right

  %p
    = form_for :new_host, url: hosts_path do |f|
      .input-group
        = f.text_field :name, class: 'form-control', placeholder: 'New Host'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
  = paginate @hosts, param_name: 'sidebar_page'

%ul.nav.nav-tabs#tabs
  %li{:class => ('active' if params['current_tab'] == 'servers' || params['current_tab'] == nil)}
    %a(href="#servers" data-toggle="tab")
      Servers 
      %span.label.label-info= @host.servers.length
  %li{:class => ('active' if params['current_tab'] == 'contacts')}
    %a(href="#contacts" data-toggle="tab")
      Contacts
      %span.label.label-info= @host.contacts.length
  %li{:class => ('active' if params['current_tab'] == 'notes')}
    %a(href="#notes" data-toggle="tab")
      Notes
      %span.label.label-info= @host.notes.length

.tab-content
  .tab-pane#servers{:class => ('active' if params['current_tab'] == 'servers' || params['current_tab'] == nil)}

    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Name
          %th(width="20%") Clients
          %th Sites
          %th(width="10%") &nbsp;
      %tbody
        - @host_servers.each do |server|
          %tr
            %td
              = best_in_place server, :name, type: :input
            %td= server.num_clients
            %td= server.num_sites
            %td
              - if server.clients.length == 0
                = link_to server_url(server, current_tab: 'servers'),
                          confirm: t('confirm.delete', name: server.name),
                          method: :delete do
                  %span.glyphicon.glyphicon-remove
              - else
                %span.glyphicon.glyphicon-remove.text-muted
              = link_to server_url(server, current_tab: 'clients') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_server, url: servers_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="servers")
        = f.text_field :name, class: 'form-control', placeholder: 'New Server'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @host_servers, param_name: 'body_page'

  .tab-pane#contacts{:class => ('active' if params['current_tab'] == 'contacts')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Last Name
          %th(width="20%") First Name
          %th Description
          %th(width="10%") &nbsp;
      %tbody
        - @host_contacts.each do |contact|
          %tr
            %td
              = best_in_place contact, :last_name, type: :input, nil: '-'
            %td
              = best_in_place contact, :first_name, type: :input, nil: '-'
            %td
              = best_in_place contact, :description, type: :input, nil: '-'
            %td
              = link_to contact_url(contact, current_tab: 'contacts'),
                        confirm: t('confirm.delete', name: contact.full_name),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to contact_url(contact, current_tab: 'contacts') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_contact, url: contacts_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="contacts")
        = f.text_field :description, class: 'form-control', placeholder: 'New Contact Description'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @host_contacts, param_name: 'body_page', params: {current_tab: 'contacts'}

  .tab-pane#notes{:class => ('active' if params['current_tab'] == 'notes')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Created On
          %th Note
          %th(width="10%") &nbsp;
      %tbody
        - @host_notes.each do |note|
          %tr
            %td
              = note.created_at
            %td
              = best_in_place note, :note, type: :textarea
            %td
              = link_to note_url(note, current_tab: 'notes'),
                        confirm: t('confirm.delete', name: "note created at #{note.created_at}"),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to note_url(note, current_tab: 'notes') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_note, url: notes_path, class: 'form-inline' do |f|
      %input(type="hidden" name="current_tab" value="notes")
      = f.text_area :note, class: 'form-control', placeholder: 'New Note'
      .spacer-v10
      = f.button class: 'btn btn-default' do
        Add Note
        %span.glyphicon.glyphicon-plus
    = paginate @host_notes, param_name: 'body_page', params: {current_tab: 'notes'}