config/routes.rb
Serverfu4::Application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "overview/index"
  root to: "overview#index"

  resources :credential_types
  resources :credentials
  resources :ips
  resources :domains
  resources :sites
  resources :clients
  resources :servers
  resources :hosts
  resources :notes
  resources :contacts
  resources :phones
  resources :emails
  resources :addresses
  resources :states
end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :notes, :as => :noteable
  has_many :contacts, :as => :contactable
  has_many :clients
  has_many :ips
  belongs_to :host

  def num_clients
    clients.length
  end

  def num_sites
    num_sites = 0
    clients.each do |client|
      num_sites += client.sites.length
    end
    num_sites
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    server = Server.find(:all, order: 'name').first
    if server != nil then
      redirect_to server_url(server)
    end
  end

  def show
    begin
      @server = Server.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to servers_path
    else
      @server_clients = @server.clients.order(:name).page params[:body_page]
      @server_ips = @server.ips.order(:address).page params[:body_page]
      @server_notes = @server.notes.order('created_at DESC').page params[:body_page]
  
      @servers = Server.order('name').page params[:sidebar_page]
  
      @new_server = Server.new
    end
  end

  def create
    if get_controller_from_state == 'hosts'
      @host = Host.find get_id_from_state
      server = @host.servers.build server_params(:new_server)
    else
      server = Server.new server_params(:new_server)
    end

    if server.save
      redirect_to_state notice: (t 'success.create', thing: 'Server')
    else
      redirect_to_state error: (t 'error.create', thing: 'Server')
    end
  end
  
  def update
    @server = Server.find params[:id]
   
    respond_to do |format|
      if @server.update_attributes(server_params)
        format.html { redirect_to @server,
          notice: (t 'success.update', thing: 'Server') }
        format.json { respond_with_bip(@server) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@server) }
      end
    end
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html {
        redirect_to_state notice: (t 'success.delete', thing: 'Server') }
      format.json { head :no_content }
    end
  end

  private

  def server_params(server_object = :server)
    params.require(server_object).permit(:name)
  end

end

app/views/servers/index.html.haml
- content_for :sidebar do
  %h3 Servers

%ul.nav.nav-tabs
  %p No servers have been added yet.

app/views/servers/show.html.haml
- content_for :sidebar do
  %ul.list-group
    - @servers.each do |server|
      %li.list-group-item{:class => ('active' if @server.id == server.id)}
        = best_in_place server, :name, type: :input
        - if server.clients.length == 0
          = link_to server_url(server, sidebar_page: params['sidebar_page']),
                    confirm: t('confirm.delete', name: server.name),
                    method: :delete do
            %span.glyphicon.glyphicon-remove
        - else
          %span.glyphicon.glyphicon-remove.text-muted
        = link_to server_url(server, sidebar_page: params['sidebar_page']) do
          %span.glyphicon.glyphicon-chevron-right
  %p
    = form_for :new_server, url: servers_path do |f|
      .input-group
        = f.text_field :name, class: 'form-control', placeholder: 'New server'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
  = paginate @servers, param_name: 'sidebar_page'

%ul.nav.nav-tabs#tabs
  %li{:class => ('active' if params['current_tab'] == 'clients' || params['current_tab'] == nil)}
    %a(href="#clients" data-toggle="tab")
      Clients 
      %span.label.label-info= @server.clients.length
  %li{:class => ('active' if params['current_tab'] == 'ips')}
    %a(href="#ips" data-toggle="tab")
      IPs
      %span.label.label-info= @server.ips.length
  %li{:class => ('active' if params['current_tab'] == 'notes')}
    %a(href="#notes" data-toggle="tab")
      Notes
      %span.label.label-info= @server.notes.length

.tab-content
  .tab-pane#clients{:class => ('active' if params['current_tab'] == 'clients' || params['current_tab'] == nil)}

    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Name
          %th(width="20%") Sites
          %th Contacts
          %th(width="10%") &nbsp;
      %tbody
        - @server_clients.each do |client|
          %tr
            %td
              = best_in_place client, :name, type: :input
            %td= client.sites.length
            %td= client.contacts.length
            %td
              - if client.sites.length == 0
                = link_to client_url(client, current_tab: 'clients'),
                          confirm: t('confirm.delete', name: client.name),
                          method: :delete do
                  %span.glyphicon.glyphicon-remove
              - else
                %span.glyphicon.glyphicon-remove.text-muted
              = link_to client_url(client, current_tab: 'client') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_client, url: clients_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="clients")
        = f.text_field :name, class: 'form-control', placeholder: 'New Client'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @server_clients, param_name: 'body_page'

  .tab-pane#ips{:class => ('active' if params['current_tab'] == 'ips')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th IP
          %th(width="10%") &nbsp;
      %tbody
        - @server_ips.each do |ip|
          %tr
            %td
              = best_in_place ip, :address
            %td
              = link_to ip_url(ip, current_tab: 'ips'),
                        confirm: t('confirm.delete', name: ip.address),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to ip_url(ip, current_tab: 'ips') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_ip, url: ips_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="ips")
        = f.text_field :address, class: 'form-control', placeholder: 'New IP'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @server_ips, param_name: 'body_page', params: {current_tab: 'ips'}

  .tab-pane#notes{:class => ('active' if params['current_tab'] == 'notes')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Created On
          %th Note
          %th(width="10%") &nbsp;
      %tbody
        - @server_notes.each do |note|
          %tr
            %td
              = note.created_at
            %td
              = best_in_place note, :note, type: :textarea
            %td
              = link_to note_url(note, current_tab: 'notes'),
                        confirm: t('confirm.delete', name: "note created at #{note.created_at}"),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to note_url(note, current_tab: 'notes') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_note, url: notes_path, class: 'form-inline' do |f|
      %input(type="hidden" name="current_tab" value="notes")
      = f.text_area :note, class: 'form-control', placeholder: 'New Note'
      .spacer-v10
      = f.button class: 'btn btn-default' do
        Add Note
        %span.glyphicon.glyphicon-plus
    = paginate @server_notes, param_name: 'body_page', params: {current_tab: 'notes'}