config/routes.rb
Serverfu4::Application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "overview/index"
  root to: "overview#index"

  resources :credential_types
  resources :credentials
  resources :ips
  resources :domains
  resources :sites
  resources :clients
  resources :servers
  resources :hosts
  resources :notes
  resources :contacts
  resources :phones
  resources :emails
  resources :addresses
  resources :states
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :notes, :as => :noteable
  has_many :contacts, :as => :contactable
  has_many :sites
  belongs_to :server

  def num_sites
    sites.length
  end

  def ip_collection
    ip_collection = []
    server.ips.order(':address').each do |ip|
      ip_collection << [ip.id, ip.address]
    end
    ip_collection
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    client = Client.find(:all, order: 'name').first
    if client != nil then
      redirect_to client_url(client)
    end
  end

  def show
    begin
      @client = Client.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to clients_path
    else
      @client_sites = @client.sites.order(:description).page params[:body_page]
      @client_contacts = @client.contacts.order(:last_name).page params[:body_page]
      @client_notes = @client.notes.order('created_at DESC').page params[:body_page]
      @clients = Client.order('name').page params[:sidebar_page]

      @new_client = Client.new
    end
  end

  def create
    if get_controller_from_state == 'servers'
      @server = Server.find get_id_from_state
      client = @server.clients.build client_params(:new_client)
    else
      client = Client.new client_params(:new_client)
      if client.server == nil
        default_server = Server.find(:all, order: 'name').first
        client.server = default_server
      end
    end

    if client.save
      redirect_to_state notice: (t 'success.create', thing: 'Client')
    else
      redirect_to_state error: (t 'error.create', thing: 'Client')
    end
  end
  
  def update
    @client = Client.find params[:id]
   
    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to @client,
          notice: (t 'success.update', thing: 'Client') }
        format.json { respond_with_bip(@client) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@client) }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      respond_to do |format|
         format.html {
           redirect_to_state notice: (t 'success.delete', thing: 'Client') }
         format.json { head :no_content }
       end
    end
  end

  private

  def client_params(client_object = :client)
    params.require(client_object).permit(:name)
  end
end

app/views/clients/index.html.haml
- content_for :sidebar do
  %h3 Clients

%ul.nav.nav-tabs
  %p No clients have been added yet.

app/views/clients/show.html.haml
- content_for :sidebar do
  %ul.list-group
    - @clients.each do |client|
      %li.list-group-item{:class => ('active' if @client.id == client.id)}
        = best_in_place client, :name, type: :input
        - if client.contacts.length == 0
          = link_to client_url(client, sidebar_page: params['sidebar_page']),
                    confirm: t('confirm.delete', name: client.name),
                    method: :delete do
            %span.glyphicon.glyphicon-remove
        - else
          %span.glyphicon.glyphicon-remove.text-muted
        = link_to client_url(client, sidebar_page: params['sidebar_page']) do
          %span.glyphicon.glyphicon-chevron-right

  %p
    = form_for :new_client, url: clients_path do |f|
      .input-group
        = f.text_field :name, class: 'form-control', placeholder: 'New Client'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
  = paginate @clients, param_name: 'sidebar_page'

%ul.nav.nav-tabs#tabs
  %li{:class => ('active' if params['current_tab'] == 'sites' || params['current_tab'] == nil)}
    %a(href="#contacts" data-toggle="tab")
      Sites
      %span.label.label-info= @client.sites.length
  %li{:class => ('active' if params['current_tab'] == 'contacts')}
    %a(href="#contacts" data-toggle="tab")
      Contacts
      %span.label.label-info= @client.contacts.length
  %li{:class => ('active' if params['current_tab'] == 'notes')}
    %a(href="#notes" data-toggle="tab")
      Notes
      %span.label.label-info= @client.notes.length

.tab-content
  .tab-pane#sites{:class => ('active' if params['current_tab'] == 'sites' || params['current_tab'] == nil)}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Description
          %th(width="20%") IP
          %th Domain Names
          %th(width="10%") &nbsp;
      %tbody
        - @client_sites.each do |site|
          %tr
            %td
              = best_in_place site, :description, type: :input, nil: '-'
            %td
              = best_in_place site, :ip_id, type: :select, nil: 'Select IP',    | 
                              collection: @client.ip_collection
            %td
              - site.domains.each do |domain|
                = domain.name
            %td
              = link_to site_url(site, current_tab: 'sites'),
                        confirm: t('confirm.delete', name: site.description),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to contact_url(site, current_tab: 'sites') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_site, url: sites_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="sites")
        = f.text_field :description, class: 'form-control', placeholder: 'New Site Description'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @client_sites, param_name: 'body_page', params: {current_tab: 'sites'}

  .tab-pane#contacts{:class => ('active' if params['current_tab'] == 'contacts')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Last Name
          %th(width="20%") First Name
          %th Description
          %th(width="10%") &nbsp;
      %tbody
        - @client_contacts.each do |contact|
          %tr
            %td
              = best_in_place contact, :last_name, type: :input, nil: '-'
            %td
              = best_in_place contact, :first_name, type: :input, nil: '-'
            %td
              = best_in_place contact, :description, type: :input, nil: '-'
            %td
              = link_to contact_url(contact, current_tab: 'contacts'),
                        confirm: t('confirm.delete', name: contact.full_name),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to contact_url(contact, current_tab: 'contacts') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_contact, url: contacts_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="contacts")
        = f.text_field :description, class: 'form-control', placeholder: 'New Contact Description'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @client_contacts, param_name: 'body_page', params: {current_tab: 'contacts'}

  .tab-pane#notes{:class => ('active' if params['current_tab'] == 'notes')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Created On
          %th Note
          %th(width="10%") &nbsp;
      %tbody
        - @client_notes.each do |note|
          %tr
            %td
              = note.created_at
            %td
              = best_in_place note, :note, type: :textarea
            %td
              = link_to note_url(note, current_tab: 'notes'),
                        confirm: t('confirm.delete', name: "note created at #{note.created_at}"),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to note_url(note, current_tab: 'notes') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_note, url: notes_path, class: 'form-inline' do |f|
      %input(type="hidden" name="current_tab" value="notes")
      = f.text_area :note, class: 'form-control', placeholder: 'New Note'
      .spacer-v10
      = f.button class: 'btn btn-default' do
        Add Note
        %span.glyphicon.glyphicon-plus
    = paginate @client_notes, param_name: 'body_page', params: {current_tab: 'notes'}