config/routes.rb
Serverfu4::Application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "overview/index"
  root to: "overview#index"

  resources :credential_types
  resources :credentials
  resources :ips
  resources :domains
  resources :sites
  resources :clients
  resources :servers
  resources :hosts
  resources :notes
  resources :contacts
  resources :phones
  resources :emails
  resources :addresses
  resources :states
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :notes, :as => :noteable
  has_many :domains
  has_many :credentials
  belongs_to :client
  belongs_to :ip
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    site = Site.find(:all, order: 'description').first
    if site != nil then
      redirect_to site_url(site)
    end
  end

  def show
    begin
      @site = Site.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to sites_path
    else
      @site_domains = @site.domains.order(:name).page params[:body_page]
      @site_notes = @site.notes.order('created_at DESC').page params[:body_page]
      @site_credentials = @site.credentials.order(:description).page params[:body_page]
  
      @sites = Site.order('description').page params[:sidebar_page]
  
      @new_site = Site.new
    end
  end

  def create
    if get_controller_from_state == 'clients'
      @client = Client.find get_id_from_state
      site = @client.sites.build site_params(:new_site)
      logger.debug "HAAERRR"
    else
      site = Site.new site_params(:new_site)
    end

    if site.save
      redirect_to_state notice: (t 'success.create', thing: 'Site')
    else
      redirect_to_state error: (t 'error.create', thing: 'Site')
    end
  end
  
  def update
    @site = Site.find params[:id]
   
    respond_to do |format|
      if @site.update_attributes(site_params)
        format.html { redirect_to @site,
          notice: (t 'success.update', thing: 'Site') }
        format.json { respond_with_bip(@site) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@site) }
      end
    end
  end

  def destroy
    @site = Site.find(params[:id])
    if @site.destroy
      respond_to do |format|
         format.html {
           redirect_to_state notice: (t 'success.delete', thing: 'Site') }
         format.json { head :no_content }
       end
    end
  end

  private

  def site_params(site_object = :site)
    params.require(site_object).permit(:description, :ip_id)
  end
end

app/views/sites/index.html.haml
- content_for :sidebar do
  %h3 Sites

%ul.nav.nav-tabs
  %p No sites have been added yet.

app/views/sites/show.html.haml
- content_for :sidebar do
  %ul.list-group
    - @sites.each do |site|
      %li.list-group-item{:class => ('active' if @site.id == site.id)}
        = best_in_place site, :description, type: :input
        - if site.domains.length == 0
          = link_to site_url(site, sidebar_page: params['sidebar_page']),
                    confirm: t('confirm.delete', name: site.description),
                    method: :delete do
            %span.glyphicon.glyphicon-remove
        - else
          %span.glyphicon.glyphicon-remove.text-muted
        = link_to site_url(site, sidebar_page: params['sidebar_page']) do
          %span.glyphicon.glyphicon-chevron-right

  %p
    = form_for :new_site, url: sites_path do |f|
      .input-group
        = f.text_field :description, class: 'form-control', placeholder: 'New Site'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
  = paginate @sites, param_name: 'sidebar_page'

%ul.nav.nav-tabs#tabs
  %li{:class => ('active' if params['current_tab'] == 'domains' || params['current_tab'] == nil)}
    %a(href="#domains" data-toggle="tab")
      Domains
      %span.label.label-info= @site.domains.length
  %li{:class => ('active' if params['current_tab'] == 'credentials')}
    %a(href="#credentials" data-toggle="tab")
      Credentials
      %span.label.label-info= @site.credentials.length
  %li{:class => ('active' if params['current_tab'] == 'notes')}
    %a(href="#notes" data-toggle="tab")
      Notes
      %span.label.label-info= @site.notes.length

.tab-content
  .tab-pane#domains{:class => ('active' if params['current_tab'] == 'domains' || params['current_tab'] == nil)}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th(width="10%") &nbsp;
      %tbody
        - @site_domains.each do |domain|
          %tr
            %td
              = best_in_place domain, :name, type: :input, nil: '-'
            %td
              = link_to site_url(site, current_tab: 'domains'),
                        confirm: t('confirm.delete', name: domain.name),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to domain_url(site, current_tab: 'sites') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_domain, url: domains_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="domains")
        = f.text_field :name, class: 'form-control', placeholder: 'New Domain Name'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @site_domains, param_name: 'body_page', params: {current_tab: 'domains'}

  .tab-pane#credentials{:class => ('active' if params['current_tab'] == 'credentials')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th Type
          %th Description
          %th(width="10%") &nbsp;
      %tbody
        - @site_credentials.each do |credentials|
          %tr
            %td
              Type coming soon ...
            %td
              = best_in_place credential, :description, type: :input, nil: '-'
            %td
              = link_to credential_url(credential, current_tab: 'credentials'),
                        confirm: t('confirm.delete', name: credential.description),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to credential_url(credential, current_tab: 'credentials') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_credential, url: contacts_path, class: 'form-inline' do |f|
      .input-group
        %input(type="hidden" name="current_tab" value="credentials")
        = f.text_field :description, class: 'form-control', placeholder: 'New Credential Description'
        %span.input-group-btn
          = f.button class: 'btn btn-default' do
            %span.glyphicon.glyphicon-plus
    = paginate @site_credentials, param_name: 'body_page', params: {current_tab: 'credentials'}

  .tab-pane#notes{:class => ('active' if params['current_tab'] == 'notes')}
    .spacer-v10
    %table.table.table-hover
      %thead
        %tr
          %th(width="30%") Created On
          %th Note
          %th(width="10%") &nbsp;
      %tbody
        - @site_notes.each do |note|
          %tr
            %td
              = note.created_at
            %td
              = best_in_place note, :note, type: :textarea
            %td
              = link_to note_url(note, current_tab: 'notes'),
                        confirm: t('confirm.delete', name: "note created at #{note.created_at}"),
                        method: :delete do
                %span.glyphicon.glyphicon-remove
              = link_to note_url(note, current_tab: 'notes') do
                %span.glyphicon.glyphicon-chevron-right
    = form_for :new_note, url: notes_path, class: 'form-inline' do |f|
      %input(type="hidden" name="current_tab" value="notes")
      = f.text_area :note, class: 'form-control', placeholder: 'New Note'
      .spacer-v10
      = f.button class: 'btn btn-default' do
        Add Note
        %span.glyphicon.glyphicon-plus
    = paginate @site_notes, param_name: 'body_page', params: {current_tab: 'notes'}